const DT=1/120, CONTROL_EVERY=4;
const STOCK_MASS_KG=0.92, STOCK_WHEELBASE_M=0.257, STOCK_TRACK_FRONT_M=0.178, STOCK_TRACK_REAR_M=0.171, STOCK_BODY_LENGTH_M=0.42, STOCK_WHEEL_RADIUS_M=0.032;
const DEFAULT_CONTROLS={pace:62,attack:42,power:50,mass:50,grip:70,rearBias:60,surface:"dry",trackId:"foundation_loop",style:"FLOW",vehicle:"BALANCED"};
const STYLE_PRESETS={CRUISE:{pace:28,attack:18},FLOW:{pace:62,attack:42},QUALIFY:{pace:88,attack:36},SHOWBOAT:{pace:54,attack:86},SEND_IT:{pace:96,attack:94}};
const VEHICLE_PRESETS={BALANCED:{power:50,mass:50,grip:70,rearBias:60},HIGH_POWER:{power:92,mass:46,grip:68,rearBias:64},LOW_GRIP:{power:55,mass:50,grip:28,rearBias:62},HEAVY:{power:58,mass:88,grip:72,rearBias:58}};
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
const lerp=(a,b,t)=>a+(b-a)*t;
function wrapPi(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a;}
function sanitizeControls(raw){return{pace:clamp(Number(raw.pace??62),0,100),attack:clamp(Number(raw.attack??42),0,100),power:clamp(Number(raw.power??50),0,100),mass:clamp(Number(raw.mass??50),0,100),grip:clamp(Number(raw.grip??70),0,100),rearBias:clamp(Number(raw.rearBias??60),35,80),surface:raw.surface==="wet"||raw.surface==="low"?raw.surface:"dry",trackId:raw.trackId==="circuit_one"?"circuit_one":"foundation_loop",style:raw.style||"CUSTOM",vehicle:raw.vehicle||"CUSTOM"};}
function strategyFromControls(c){const p=c.pace/100,a=c.attack/100,targetSpeedMps=lerp(1.15,3.85,p);return{targetSpeedMps,entrySpeedMps:targetSpeedMps*lerp(0.72,0.96,a),targetSlipRad:((12+a*36)*Math.PI)/180,lineOffsetM:lerp(0.02,0.16,a)*(a>0.55?1:0.6),throttleCommit:lerp(0.42,1,0.35*p+0.65*a),brakeMargin:lerp(0.38,0.08,p),recoveryYawThresh:lerp(4.2,7.8,a),riskTolerance:clamp(0.2+a*0.7+p*0.15,0,1),lookAheadM:lerp(0.7,1.8,0.55*p+0.45*a)};}
function plantFromControls(c){const surfaceMul=c.surface==="wet"?0.62:c.surface==="low"?0.74:1;const gripMul=lerp(0.42,1.08,c.grip/100)*surfaceMul;const massKg=STOCK_MASS_KG*lerp(0.78,1.39,c.mass/100);const torque=lerp(0.14,0.34,c.power/100);const rearFrac=c.rearBias/100;return{massKg,frontStaticFraction:1-rearFrac,wheelbaseM:STOCK_WHEELBASE_M,trackWidthFrontM:STOCK_TRACK_FRONT_M,trackWidthRearM:STOCK_TRACK_REAR_M,bodyLengthM:STOCK_BODY_LENGTH_M,yawInertia:0.0075*(massKg/STOCK_MASS_KG),wheelRadiusM:STOCK_WHEEL_RADIUS_M,maxSteerRad:55*Math.PI/180,steerRateRadS:620*Math.PI/180,maxMotorTorqueNm:torque,maxBrakeTorqueNm:0.42,rollingResistanceN:0.16*(massKg/STOCK_MASS_KG),aeroDrag:0.035,frontMu:0.78*gripMul,rearMu:0.61*gripMul*lerp(0.92,1.08,rearFrac),frontCornering:7.8*gripMul,rearCornering:5.2*gripMul};}
function samplePath(raw,widthFn){const closed=raw.concat([raw[0]]);const dense=[];for(let i=0;i<closed.length-1;i++){const a=closed[i],b=closed[i+1];const d=Math.hypot(b[0]-a[0],b[1]-a[1]);const n=Math.max(6,Math.ceil(d/0.08));for(let k=0;k<n;k++){const t=k/n;dense.push([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]);}}const pts=[];let s=0;for(let i=0;i<dense.length;i++){const prev=dense[(i-1+dense.length)%dense.length],cur=dense[i],next=dense[(i+1)%dense.length];const dx=next[0]-prev[0],dy=next[1]-prev[1];const len=Math.hypot(dx,dy)||1;const tx=dx/len,ty=dy/len;s+=Math.hypot(cur[0]-prev[0],cur[1]-prev[1]);const ux=next[0]-cur[0],uy=next[1]-cur[1],vx=cur[0]-prev[0],vy=cur[1]-prev[1];const cross=vx*uy-vy*ux;const l1=Math.hypot(vx,vy)||1,l2=Math.hypot(ux,uy)||1;const kappa=cross/(l1*l2*((l1+l2)*0.5));pts.push({x:cur[0],y:cur[1],tx,ty,nx:-ty,ny:tx,kappa,s,width:widthFn(i/dense.length)});}return pts;}
function circuitOneRaw(){return[[0,0],[4.2,0.1],[7.1,0.9],[8.4,2.6],[8,4.6],[6.2,5.7],[4.4,5.2],[3.2,3.6],[2.1,3.4],[0.6,4.7],[-1.5,5.8],[-3.8,5.4],[-5.6,3.7],[-5.9,1.4],[-4.3,-0.3],[-2,-0.15]];}
function foundationRaw(){const out=[];for(let i=0;i<96;i++){const a=(i/96)*Math.PI*2;out.push([Math.cos(a)*3,Math.sin(a)*3]);}return out;}
function buildTrack(id){const raw=id==="circuit_one"?circuitOneRaw():foundationRaw();const widthFn=id==="circuit_one"?(u)=>1.20+0.08*Math.sin(u*Math.PI*4):()=>1.20;const points=samplePath(raw,widthFn);const p0=points[0];return{id,length:points[points.length-1]?.s||1,points,start:{x:p0.x,y:p0.y,yaw:Math.atan2(p0.ty,p0.tx)}};}
function lookAheadPoint(track,index,meters){const n=track.points.length,s0=track.points[index].s;let target=s0+meters;while(target>=track.length)target-=track.length;while(target<0)target+=track.length;let best=index,bestD=Infinity;for(let k=0;k<n;k++){const i=(index+k)%n;const d=Math.abs(track.points[i].s-target);const wrap=Math.min(d,track.length-d);if(wrap<bestD){bestD=wrap;best=i;}if(k>12&&wrap>bestD+0.35)break;}return track.points[best];}
function locateOnTrack(track,x,y,lastIndex=0){const n=track.points.length;const start=((lastIndex%n)+n)%n;let best=start,bestScore=Infinity;const back=8,fwd=Math.max(24,Math.floor(n*0.45));for(let k=-back;k<=fwd;k++){const i=(start+k+n*4)%n;const p=track.points[i];const d2=(p.x-x)*(p.x-x)+(p.y-y)*(p.y-y);const score=d2+(k<0?0.08*k*k:0);if(score<bestScore){bestScore=score;best=i;}}const p=track.points[best];const offset=(x-p.x)*p.nx+(y-p.y)*p.ny;return{index:best,point:p,offset,inside:Math.abs(offset)<p.width*0.5,progress:p.s/track.length};}
function createState(track){const yaw=track.start.yaw,speed=1.55;return{x:track.start.x,y:track.start.y,yaw,vx:Math.cos(yaw)*speed,vy:Math.sin(yaw)*speed,yawRate:0,steer:0,throttle:0.35,brake:0,slipRad:0,speed,progress:0,lap:0,sector:1,lastProgress:0,trackIndex:0,stalledS:0,offTrackS:0,contactCount:0,spinCount:0,recoverS:0,phase:"SETUP",continuity:1,lastContactS:99};}
function tireForce(slip,load,mu,stiffness){const cap=mu*load,raw=stiffness*slip,mag=Math.abs(raw);if(mag<=cap)return raw;return Math.sign(raw)*(cap+(mag-cap)/(1+(mag-cap)/(cap+0.01)));}
function stepPhysics(state,cmd,plant,track,dt){const next={...state};const steerTarget=clamp(cmd.steer,-plant.maxSteerRad,plant.maxSteerRad);const maxDs=plant.steerRateRadS*dt;next.steer+=clamp(steerTarget-next.steer,-maxDs,maxDs);next.throttle=clamp(cmd.throttle,-0.35,1);next.brake=clamp(cmd.brake,0,1);const c=Math.cos(next.yaw),s=Math.sin(next.yaw);const ux=next.vx*c+next.vy*s,uy=-next.vx*s+next.vy*c;const lf=plant.wheelbaseM*(1-plant.frontStaticFraction),lr=plant.wheelbaseM*plant.frontStaticFraction;const g=9.81,fzF=plant.massKg*g*plant.frontStaticFraction,fzR=plant.massKg*g*(1-plant.frontStaticFraction);const vfY=uy+next.yawRate*lf,vrY=uy-next.yawRate*lr;const aF=Math.atan2(vfY,Math.max(0.25,ux))-next.steer;const aR=Math.atan2(vrY,Math.max(0.25,ux));next.slipRad=aR;const FyF=-tireForce(aF,fzF,plant.frontMu,plant.frontCornering);const FyR=-tireForce(aR,fzR,plant.rearMu,plant.rearCornering);const drive=next.throttle>=0?(next.throttle*plant.maxMotorTorqueNm)/plant.wheelRadiusM:(next.throttle*plant.maxBrakeTorqueNm)/plant.wheelRadiusM;const brakeF=-(next.brake*plant.maxBrakeTorqueNm)/plant.wheelRadiusM;let FxR=clamp(drive+brakeF,-plant.rearMu*fzR,plant.rearMu*fzR);const comb=Math.hypot(FxR/Math.max(0.01,plant.rearMu*fzR),FyR/Math.max(0.01,plant.rearMu*fzR));if(comb>1)FxR/=comb;const drag=-Math.sign(ux||1)*(plant.rollingResistanceN+plant.aeroDrag*ux*ux);const Fx=FxR+drag,Fy=FyF*Math.cos(next.steer)+FyR;const axBody=Fx/plant.massKg+uy*next.yawRate,ayBody=Fy/plant.massKg-ux*next.yawRate;const yawAcc=(FyF*Math.cos(next.steer)*lf-FyR*lr+FxR*0.02)/plant.yawInertia;const axW=axBody*c-ayBody*s,ayW=axBody*s+ayBody*c;next.vx+=axW*dt;next.vy+=ayW*dt;next.yawRate+=yawAcc*dt;next.yaw=wrapPi(next.yaw+next.yawRate*dt);next.x+=next.vx*dt;next.y+=next.vy*dt;next.speed=Math.hypot(next.vx,next.vy);const loc=locateOnTrack(track,next.x,next.y,next.trackIndex);next.trackIndex=loc.index;const half=loc.point.width*0.5;if(Math.abs(loc.offset)>half){const pen=Math.abs(loc.offset)-half,sign=Math.sign(loc.offset)||1;next.x-=loc.point.nx*sign*pen;next.y-=loc.point.ny*sign*pen;const vn=next.vx*loc.point.nx+next.vy*loc.point.ny;next.vx-=loc.point.nx*vn*0.55;next.vy-=loc.point.ny*vn*0.55;next.lastContactS=0;if(pen>0.06)next.contactCount+=1;next.offTrackS+=dt;}else{next.offTrackS=Math.max(0,next.offTrackS-dt*2);next.lastContactS+=dt;}const wrapped=loc.progress;if(wrapped+0.7<next.lastProgress)next.lap+=1;next.lastProgress=wrapped;next.progress=wrapped;next.sector=Math.min(4,1+Math.floor(wrapped*4));if(next.speed<0.18)next.stalledS+=dt;else next.stalledS=0;if(Math.abs(next.yawRate)>8.5&&next.speed<0.7)next.spinCount+=1;const headingErr=Math.abs(wrapPi(Math.atan2(loc.point.ty,loc.point.tx)-next.yaw));const lineErr=Math.min(1,Math.abs(loc.offset)/Math.max(0.2,half));next.continuity=clamp(next.continuity*0.98+0.02*(1-0.45*lineErr-(0.25*headingErr)/Math.PI),0,1);if(next.lastContactS<0.4)next.continuity*=0.92;return next;}
function choosePhase(state,env,locOffset,kappa){if(state.recoverS>0||state.stalledS>0.85||Math.abs(state.yawRate)>env.recoveryYawThresh+2.2)return state.stalledS>1.4?"CONTROL_LOST":"RECOVER";const slip=Math.abs(state.slipRad),speed=state.speed;if(speed<env.entrySpeedMps*0.62)return"SETUP";if(slip<env.targetSlipRad*0.28)return speed>env.entrySpeedMps*0.82?"INITIATE":"ENTRY";if(slip<env.targetSlipRad*0.62)return"INITIATE";if(Math.abs(locOffset)>0.42)return"STABILIZE";return"DRIFT";}
function kairosControl(state,env,track,plant){const loc=locateOnTrack(track,state.x,state.y,state.trackIndex);const lookNear=lookAheadPoint(track,loc.index,Math.max(0.45,env.lookAheadM*0.45));const lookFar=lookAheadPoint(track,loc.index,env.lookAheadM);const phase=choosePhase(state,env,loc.offset,lookNear.kappa);const look=phase==="ENTRY"||phase==="SETUP"||phase==="INITIATE"?lookNear:lookFar;const pathYaw=Math.atan2(look.ty,look.tx);const turnSign=Math.sign(look.kappa||loc.point.kappa||1);const holdYaw=wrapPi(pathYaw-turnSign*env.targetSlipRad*0.82);const pathYawErr=wrapPi(pathYaw-state.yaw);const holdYawErr=wrapPi(holdYaw-state.yaw);const desiredOffset=-turnSign*env.lineOffsetM;const offsetErr=loc.offset-desiredOffset;const slipErr=Math.abs(state.slipRad)-env.targetSlipRad;const speedTarget=phase==="ENTRY"||phase==="SETUP"?env.entrySpeedMps:env.targetSpeedMps;const speedErr=speedTarget-state.speed;const routeYaw=state.speed*look.kappa;const yawRateErr=routeYaw-state.yawRate;let steer=0,throttle=0,brake=0;if(phase==="RECOVER"||phase==="CONTROL_LOST"){steer=clamp(-state.yawRate*0.1-pathYawErr*0.85-offsetErr*0.7,-plant.maxSteerRad,plant.maxSteerRad);throttle=state.speed>0.7?0.08:0.28;brake=state.speed>2.2?0.22:0;}else if(phase==="SETUP"){steer=clamp(pathYawErr*1.05-offsetErr*0.7,-0.35,0.35);throttle=clamp(0.38+Math.max(0,speedErr)*0.28,0.22,0.7);}else if(phase==="ENTRY"){steer=clamp(pathYawErr*1.05-offsetErr*0.55+turnSign*0.08,-plant.maxSteerRad,plant.maxSteerRad);throttle=clamp(0.32+Math.max(0,speedErr)*0.3,0.18,0.7);if(speedErr<-0.35)brake=clamp(-speedErr*env.brakeMargin*0.4,0,0.4);}else if(phase==="INITIATE"){steer=clamp(turnSign*lerp(0.24,0.48,env.riskTolerance)+pathYawErr*0.18,-plant.maxSteerRad,plant.maxSteerRad);throttle=clamp(0.62+env.throttleCommit*0.28,0.4,1);brake=env.targetSlipRad>0.28?0.16:0.08;}else if(phase==="DRIFT"){const counter=-Math.sign(state.slipRad||turnSign);steer=clamp(holdYawErr*0.95+counter*(0.12+Math.max(0,slipErr)*0.55)-offsetErr*0.35+yawRateErr*0.08,-plant.maxSteerRad,plant.maxSteerRad);throttle=clamp(0.46+env.throttleCommit*0.38-Math.max(0,slipErr)*0.85+Math.max(0,-slipErr)*0.4+Math.max(0,speedErr)*0.12,0.16,1);}else{steer=clamp(pathYawErr*0.9-offsetErr*0.85-state.yawRate*0.06,-plant.maxSteerRad,plant.maxSteerRad);throttle=clamp(0.28+speedErr*0.22,0.12,0.7);}return{cmd:{steer,throttle,brake},phase};}
class KairosRuntime{
  constructor(controls={},seed=1){this.seed=seed;this.controls=sanitizeControls({...DEFAULT_CONTROLS,...controls});this.track=buildTrack(this.controls.trackId);this.state=createState(this.track);this.env=strategyFromControls(this.controls);this.plant=plantFromControls(this.controls);this.command={steer:0,throttle:0.35,brake:0};this.time=0;this.steps=0;this.paused=false;this.lapClock=0;this.lastLapTime=null;this.lastLap=0;this.recoveries=0;this.trail=[];this.skids=[];this.samples=[];}
  setLiveControls(next){const prev=this.controls.trackId;this.controls=sanitizeControls({...this.controls,...next});this.env=strategyFromControls(this.controls);this.plant=plantFromControls(this.controls);if(this.controls.trackId!==prev)this.resetCar();}
  resetCar(){this.track=buildTrack(this.controls.trackId);this.state=createState(this.track);this.command={steer:0,throttle:0.35,brake:0};this.time=0;this.steps=0;this.lapClock=0;this.lastLapTime=null;this.lastLap=0;this.recoveries=0;this.trail=[];this.skids=[];this.samples=[];this.paused=false;}
  resetSetup(){this.controls={...DEFAULT_CONTROLS};this.env=strategyFromControls(this.controls);this.plant=plantFromControls(this.controls);this.resetCar();}
  step(dt=DT){if(this.paused)return;if(this.steps%CONTROL_EVERY===0){const decided=kairosControl(this.state,this.env,this.track,this.plant);this.command=decided.cmd;const was=this.state.phase==="RECOVER"||this.state.phase==="CONTROL_LOST";this.state.phase=decided.phase;if(!was&&(this.state.phase==="RECOVER"||this.state.phase==="CONTROL_LOST")){this.recoveries+=1;this.state.recoverS=0.55;}}if(this.state.recoverS>0)this.state.recoverS=Math.max(0,this.state.recoverS-dt);this.state=stepPhysics(this.state,this.command,this.plant,this.track,dt);this.time+=dt;this.steps+=1;this.lapClock+=dt;if(this.state.lap>this.lastLap){this.lastLapTime=this.lapClock;this.lapClock=0;this.lastLap=this.state.lap;}if(this.steps%3===0){this.trail.push({x:this.state.x,y:this.state.y});if(this.trail.length>420)this.trail.shift();if(Math.abs(this.state.slipRad)>0.18){this.skids.push({x:this.state.x,y:this.state.y,life:1});if(this.skids.length>900)this.skids.shift();}}for(const skid of this.skids)skid.life=Math.max(0,skid.life-dt*0.045);if(this.steps%6===0){this.samples.push({speed:this.state.speed,slipDeg:this.state.slipRad*180/Math.PI});if(this.samples.length>240)this.samples.shift();}}
  summarize(label){const slips=this.samples.map(s=>Math.abs(s.slipDeg));const speeds=this.samples.map(s=>s.speed);const avg=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;return{id:label,label,avgSpeed:avg(speeds),avgSlipDeg:avg(slips),continuity:this.state.continuity,pace:this.controls.pace,attack:this.controls.attack};}
}
const rt=new KairosRuntime(DEFAULT_CONTROLS,7);
let camera="CHASE",advanced=false,runs=[];
const cam={x:0,y:0,a:0,z:180};
const canvas=document.getElementById("view");
const ctx=canvas.getContext("2d");
function fit(){const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);}
function drawChassis(x,y,yaw,steer,slip){const L=STOCK_BODY_LENGTH_M,wf=STOCK_TRACK_FRONT_M,wr=STOCK_TRACK_REAR_M,wb=STOCK_WHEELBASE_M,axleF=wb*0.6,axleR=-wb*0.4;ctx.save();ctx.translate(x,y);ctx.rotate(yaw);ctx.fillStyle="rgba(0,0,0,0.35)";ctx.beginPath();ctx.ellipse(0.01,0.02,L*0.42,wf*0.62,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#2a271f";ctx.fillRect(-L*0.46,-wf*0.28,L*0.9,wf*0.56);ctx.fillStyle="#c8b88a";ctx.fillRect(-L*0.44,-wf*0.22,L*0.86,wf*0.44);ctx.fillStyle="#1a1914";ctx.fillRect(-0.07,-0.045,0.13,0.09);ctx.fillStyle="#8a7a4e";ctx.fillRect(0.08,-0.03,0.05,0.06);ctx.fillStyle="#4a4638";ctx.fillRect(-0.16,-0.035,0.07,0.07);ctx.strokeStyle="#efe6c9";ctx.lineWidth=0.006;ctx.beginPath();ctx.moveTo(axleF,-wf*0.5);ctx.lineTo(axleF,wf*0.5);ctx.moveTo(axleR,-wr*0.5);ctx.lineTo(axleR,wr*0.5);ctx.stroke();const tire=(tx,ty,rot=0)=>{ctx.save();ctx.translate(tx,ty);ctx.rotate(rot);ctx.fillStyle="#11100c";ctx.fillRect(-0.032,-0.014,0.064,0.028);ctx.fillStyle="#efe6c9";ctx.fillRect(-0.018,-0.01,0.036,0.02);ctx.restore();};tire(axleF,-wf*0.5,steer);tire(axleF,wf*0.5,steer);tire(axleR,-wr*0.5);tire(axleR,wr*0.5);if(Math.abs(slip)>0.2){ctx.fillStyle="rgba(210,210,210,0.22)";ctx.beginPath();ctx.ellipse(axleR-0.05,wr*0.28,0.1,0.028,0,0,Math.PI*2);ctx.fill();}ctx.restore();}
function draw(){const w=canvas.width,h=canvas.height,st=rt.state;ctx.fillStyle="#07080b";ctx.fillRect(0,0,w,h);const look=camera==="TOP"?0:st.yaw-Math.PI/2;const viewM=camera==="TOP"?8.2:camera==="CINEMATIC"?4.4:2.7;const targetZ=Math.min(w,h)/viewM;cam.x+=(st.x-cam.x)*0.12;cam.y+=(st.y-cam.y)*0.12;cam.a+=Math.atan2(Math.sin(look-cam.a),Math.cos(look-cam.a))*0.14;cam.z+=(targetZ-cam.z)*0.1;ctx.save();ctx.translate(w*0.5,h*(camera==="TOP"?0.5:0.64));ctx.rotate(camera==="TOP"?0:-cam.a);ctx.scale(cam.z,cam.z);ctx.translate(-cam.x,-cam.y);ctx.strokeStyle="rgba(214,196,140,0.08)";ctx.lineWidth=0.01;for(let x=-12;x<=12;x+=0.25){ctx.beginPath();ctx.moveTo(x,-12);ctx.lineTo(x,12);ctx.stroke();}for(let y=-12;y<=12;y+=0.25){ctx.beginPath();ctx.moveTo(-12,y);ctx.lineTo(12,y);ctx.stroke();}ctx.strokeStyle="rgba(214,196,140,0.18)";ctx.lineWidth=0.016;for(let x=-12;x<=12;x+=1){ctx.beginPath();ctx.moveTo(x,-12);ctx.lineTo(x,12);ctx.stroke();}for(let y=-12;y<=12;y+=1){ctx.beginPath();ctx.moveTo(-12,y);ctx.lineTo(12,y);ctx.stroke();}const pts=rt.track.points;ctx.fillStyle="#17150f";ctx.beginPath();pts.forEach((p,i)=>{const x=p.x+p.nx*p.width*0.5,y=p.y+p.ny*p.width*0.5;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});for(let i=pts.length-1;i>=0;i--){const p=pts[i];ctx.lineTo(p.x-p.nx*p.width*0.5,p.y-p.ny*p.width*0.5);}ctx.closePath();ctx.fill();ctx.strokeStyle="#d6c48c";ctx.lineWidth=0.018;ctx.stroke();ctx.strokeStyle="rgba(232,228,216,0.18)";ctx.setLineDash([0.08,0.1]);ctx.lineWidth=0.012;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.setLineDash([]);for(const skid of rt.skids){if(skid.life<=0)continue;ctx.fillStyle=`rgba(38,34,26,${0.38*skid.life})`;ctx.beginPath();ctx.arc(skid.x,skid.y,0.028,0,Math.PI*2);ctx.fill();}ctx.strokeStyle="rgba(214,196,140,0.5)";ctx.lineWidth=0.014;ctx.beginPath();rt.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();drawChassis(st.x,st.y,st.yaw,st.steer,st.slipRad);ctx.restore();}
function fmt(n,d=1){return Number.isFinite(n)?n.toFixed(d):"-";}
function renderHUD(){const st=rt.state;document.getElementById("tSpeed").textContent=fmt(st.speed,2)+" m/s";document.getElementById("tSlip").textContent=fmt(st.slipRad*180/Math.PI,0)+" deg";document.getElementById("tPhase").textContent=st.phase;document.getElementById("tLap").textContent=st.lap+" / S"+st.sector;document.getElementById("tCont").textContent=fmt(st.continuity*100,0);document.getElementById("hint").textContent=st.phase==="CONTROL_LOST"?"CONTROL LOST — recovering without a teleport.":st.phase==="RECOVER"?"RECOVERING — Kairos is restabilizing on the ribbon.":`1:1 RMX 2.5 · ${fmt(rt.plant.massKg,2)} kg · 257 mm WB.`;document.getElementById("note").textContent=`Stock 0.92 kg / 257 mm WB / 178/171 mm track. Target ${fmt(rt.env.targetSpeedMps,2)} m/s, slip ${fmt(rt.env.targetSlipRad*180/Math.PI,0)} deg, look ${fmt(rt.env.lookAheadM,2)} m.`;document.getElementById("paceEm").textContent=rt.controls.pace+" / "+fmt(rt.env.targetSpeedMps,2)+" m/s";document.getElementById("attackEm").textContent=rt.controls.attack+" / "+fmt(rt.env.targetSlipRad*180/Math.PI,0)+" deg";document.getElementById("lPower").textContent="POWER "+rt.controls.power;document.getElementById("lMass").textContent="MASS "+rt.controls.mass+" → "+fmt(rt.plant.massKg,2)+" kg";document.getElementById("lGrip").textContent="GRIP "+rt.controls.grip;document.getElementById("lBias").textContent="REAR BIAS "+rt.controls.rearBias;const pause=document.getElementById("pause");pause.className=rt.paused?"is-on":"";pause.innerHTML=rt.paused?"RESUME<em>held</em>":"PAUSE<em>live</em>";}
function chip(label,on,fn){const b=document.createElement("button");b.className="kl-chip"+(on?" is-on":"");b.textContent=label;b.onclick=fn;return b;}
function refreshChips(){const presets=document.getElementById("presets");presets.innerHTML="";Object.keys(STYLE_PRESETS).forEach(id=>presets.appendChild(chip(id.replace("_"," "),rt.controls.style===id,()=>{Object.assign(rt.controls,STYLE_PRESETS[id],{style:id});syncSliders();rt.setLiveControls(rt.controls);refreshChips();})));Object.keys(VEHICLE_PRESETS).forEach(id=>presets.appendChild(chip(id.replace("_"," "),rt.controls.vehicle===id,()=>{Object.assign(rt.controls,VEHICLE_PRESETS[id],{vehicle:id});syncSliders();rt.setLiveControls(rt.controls);refreshChips();})));presets.appendChild(chip(advanced?"HIDE ADVANCED":"CAR / TRACK",advanced,()=>{advanced=!advanced;document.getElementById("side").classList.toggle("is-open",advanced);refreshChips();}));const cams=document.getElementById("cams");cams.innerHTML="";["CHASE","CINEMATIC","TOP"].forEach(m=>{const b=document.createElement("button");b.className=camera===m?"is-on":"";b.textContent=m;b.onclick=()=>{camera=m;refreshChips();};cams.appendChild(b);});const surfaces=document.getElementById("surfaces");surfaces.innerHTML="";["dry","low","wet"].forEach(s=>{const b=document.createElement("button");b.className=rt.controls.surface===s?"is-on":"";b.textContent=s.toUpperCase();b.onclick=()=>{rt.controls.surface=s;rt.setLiveControls(rt.controls);refreshChips();};surfaces.appendChild(b);});const tracks=document.getElementById("tracks");tracks.innerHTML="";[["foundation_loop","LOOP Ø6 m"],["circuit_one","CIRCUIT"]].forEach(([id,label])=>{const b=document.createElement("button");b.className=rt.controls.trackId===id?"is-on":"";b.textContent=label;b.onclick=()=>{rt.controls.trackId=id;rt.setLiveControls(rt.controls);refreshChips();};tracks.appendChild(b);});}
function syncSliders(){["pace","attack","power","mass","grip","rearBias"].forEach(k=>{document.getElementById(k).value=rt.controls[k];});}
["pace","attack","power","mass","grip","rearBias"].forEach(k=>{document.getElementById(k).addEventListener("input",e=>{rt.controls[k]=Number(e.target.value);if(k==="pace"||k==="attack")rt.controls.style="CUSTOM";else rt.controls.vehicle="CUSTOM";rt.setLiveControls(rt.controls);refreshChips();});});
function paintRuns(){document.getElementById("runs").innerHTML=runs.map(r=>`<div><strong>${r.label}</strong><div>P${r.pace} A${r.attack}</div><div>avg ${fmt(r.avgSpeed,2)} m/s</div><div>slip ${fmt(r.avgSlipDeg,0)}</div><div>cont ${fmt(r.continuity*100,0)}</div></div>`).join("");}
document.getElementById("resetCar").onclick=()=>{rt.resetCar();renderHUD();};
document.getElementById("resetRun").onclick=()=>{rt.resetCar();runs=[];paintRuns();renderHUD();};
document.getElementById("resetSetup").onclick=()=>{rt.resetSetup();syncSliders();runs=[];paintRuns();refreshChips();renderHUD();};
document.getElementById("pause").onclick=()=>{rt.paused=!rt.paused;renderHUD();};
document.getElementById("store").onclick=()=>{runs=[rt.summarize("R"+(runs.length+1)),...runs].slice(0,4);paintRuns();};
fit();refreshChips();renderHUD();window.addEventListener("resize",fit);
let last=performance.now(),acc=0;
function loop(now){requestAnimationFrame(loop);const raw=Math.min(0.05,(now-last)/1000);last=now;acc+=raw;while(acc>=DT){rt.step(DT);acc-=DT;}draw();if(rt.steps%8===0)renderHUD();}
requestAnimationFrame(loop);
