class KairosRuntime{
  constructor(controls={},seed=1){this.seed=seed;this.controls=sanitizeControls({...DEFAULT_CONTROLS,...controls});this.track=buildTrack(this.controls.trackId);this.state=createState(this.track);this.env=strategyFromControls(this.controls);this.plant=plantFromControls(this.controls);this.command={steer:0,throttle:0.42,brake:0};this.decision=null;this.time=0;this.steps=0;this.paused=false;this.lapClock=0;this.lastLapTime=null;this.lastLap=0;this.recoveries=0;this.trail=[];this.skids=[];this.samples=[];}
  setLiveControls(next){const prev=this.controls.trackId;this.controls=sanitizeControls({...this.controls,...next});this.env=strategyFromControls(this.controls);this.plant=plantFromControls(this.controls);if(this.controls.trackId!==prev)this.resetCar();}
  resetCar(){this.track=buildTrack(this.controls.trackId);this.state=createState(this.track);this.command={steer:0,throttle:0.42,brake:0};this.decision=null;this.time=0;this.steps=0;this.lapClock=0;this.lastLapTime=null;this.lastLap=0;this.recoveries=0;this.trail=[];this.skids=[];this.samples=[];this.paused=false;}
  resetSetup(){this.controls={...DEFAULT_CONTROLS};this.env=strategyFromControls(this.controls);this.plant=plantFromControls(this.controls);this.resetCar();}
  step(dt=DT){if(this.paused)return;if(this.steps%CONTROL_EVERY===0){const decided=kairosControl(this.state,this.env,this.track,this.plant);this.command=decided.cmd;this.decision=decided;if(this.state.phase!==decided.phase)this.state.phaseHoldS=0;const was=this.state.phase==="RECOVER"||this.state.phase==="CONTROL_LOST";this.state.phase=decided.phase;if(!was&&(this.state.phase==="RECOVER"||this.state.phase==="CONTROL_LOST")){this.recoveries+=1;this.state.recoverS=0.45;}}this.state.phaseHoldS=(this.state.phaseHoldS||0)+dt;if(this.state.recoverS>0)this.state.recoverS=Math.max(0,this.state.recoverS-dt);this.state=stepPhysics(this.state,this.command,this.plant,this.track,dt);if(this.decision)this.state=projectEnvelope(this.state,this.decision);this.time+=dt;this.steps+=1;this.lapClock+=dt;if(this.state.lap>this.lastLap){this.lastLapTime=this.lapClock;this.lapClock=0;this.lastLap=this.state.lap;}if(this.steps%3===0){this.trail.push({x:this.state.x,y:this.state.y});if(this.trail.length>420)this.trail.shift();if(Math.abs(this.state.slipRad)>0.18){this.skids.push({x:this.state.x,y:this.state.y,life:1});if(this.skids.length>900)this.skids.shift();}}for(const skid of this.skids)skid.life=Math.max(0,skid.life-dt*0.045);if(this.steps%6===0){this.samples.push({speed:this.state.speed,slipDeg:this.state.slipRad*180/Math.PI});if(this.samples.length>240)this.samples.shift();}}
  summarize(label){const slips=this.samples.map(s=>Math.abs(s.slipDeg));const speeds=this.samples.map(s=>s.speed);const avg=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;return{id:label,label,avgSpeed:avg(speeds),avgSlipDeg:avg(slips),continuity:this.state.continuity,pace:this.controls.pace,attack:this.controls.attack};}
}
const rt=new KairosRuntime(DEFAULT_CONTROLS,7);
let camera="CHASE",advanced=false,runs=[];
const cam={x:0,y:0,a:0,z:180};
const canvas=document.getElementById("view");
const ctx=canvas.getContext("2d");
function fit(){const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);}
function drawChassis(x,y,yaw,steer,slip){const L=STOCK_BODY_LENGTH_M,wf=STOCK_TRACK_FRONT_M,wr=STOCK_TRACK_REAR_M,wb=STOCK_WHEELBASE_M,axleF=wb*0.6,axleR=-wb*0.4;ctx.save();ctx.translate(x,y);ctx.rotate(yaw);ctx.fillStyle="rgba(0,0,0,0.35)";ctx.beginPath();ctx.ellipse(0.01,0.02,L*0.42,wf*0.62,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#2a271f";ctx.fillRect(-L*0.46,-wf*0.28,L*0.9,wf*0.56);ctx.fillStyle="#c8b88a";ctx.fillRect(-L*0.44,-wf*0.22,L*0.86,wf*0.44);ctx.fillStyle="#1a1914";ctx.fillRect(-0.07,-0.045,0.13,0.09);ctx.fillStyle="#8a7a4e";ctx.fillRect(0.08,-0.03,0.05,0.06);ctx.fillStyle="#4a4638";ctx.fillRect(-0.16,-0.035,0.07,0.07);ctx.strokeStyle="#efe6c9";ctx.lineWidth=0.006;ctx.beginPath();ctx.moveTo(axleF,-wf*0.5);ctx.lineTo(axleF,wf*0.5);ctx.moveTo(axleR,-wr*0.5);ctx.lineTo(axleR,wr*0.5);ctx.stroke();const tire=(tx,ty,rot=0)=>{ctx.save();ctx.translate(tx,ty);ctx.rotate(rot);ctx.fillStyle="#11100c";ctx.fillRect(-0.032,-0.014,0.064,0.028);ctx.fillStyle="#efe6c9";ctx.fillRect(-0.018,-0.01,0.036,0.02);ctx.restore();};tire(axleF,-wf*0.5,steer);tire(axleF,wf*0.5,steer);tire(axleR,-wr*0.5);tire(axleR,wr*0.5);if(Math.abs(slip)>0.2){ctx.fillStyle="rgba(210,210,210,0.22)";ctx.beginPath();ctx.ellipse(axleR-0.05,wr*0.28,0.1,0.028,0,0,Math.PI*2);ctx.fill();}ctx.restore();}
function drawAim(x,y,yaw){ctx.save();ctx.translate(x,y);ctx.rotate(yaw);ctx.fillStyle="#d6c48c";ctx.beginPath();ctx.moveTo(0.09,0);ctx.lineTo(-0.05,-0.045);ctx.lineTo(-0.05,0.045);ctx.closePath();ctx.fill();ctx.restore();}
function draw(){const w=canvas.width,h=canvas.height,st=rt.state;ctx.fillStyle="#07080b";ctx.fillRect(0,0,w,h);const look=camera==="TOP"?0:st.yaw-Math.PI/2;const viewM=camera==="TOP"?8.2:camera==="CINEMATIC"?4.4:2.7;const targetZ=Math.min(w,h)/viewM;cam.x+=(st.x-cam.x)*0.12;cam.y+=(st.y-cam.y)*0.12;cam.a+=Math.atan2(Math.sin(look-cam.a),Math.cos(look-cam.a))*0.14;cam.z+=(targetZ-cam.z)*0.1;ctx.save();ctx.translate(w*0.5,h*(camera==="TOP"?0.5:0.64));ctx.rotate(camera==="TOP"?0:-cam.a);ctx.scale(cam.z,cam.z);ctx.translate(-cam.x,-cam.y);ctx.strokeStyle="rgba(214,196,140,0.08)";ctx.lineWidth=0.01;for(let x=-12;x<=12;x+=0.25){ctx.beginPath();ctx.moveTo(x,-12);ctx.lineTo(x,12);ctx.stroke();}for(let y=-12;y<=12;y+=0.25){ctx.beginPath();ctx.moveTo(-12,y);ctx.lineTo(12,y);ctx.stroke();}ctx.strokeStyle="rgba(214,196,140,0.18)";ctx.lineWidth=0.016;for(let x=-12;x<=12;x+=1){ctx.beginPath();ctx.moveTo(x,-12);ctx.lineTo(x,12);ctx.stroke();}for(let y=-12;y<=12;y+=1){ctx.beginPath();ctx.moveTo(-12,y);ctx.lineTo(12,y);ctx.stroke();}const pts=rt.track.points;ctx.fillStyle="#17150f";ctx.beginPath();pts.forEach((p,i)=>{const x=p.x+p.nx*p.width*0.5,y=p.y+p.ny*p.width*0.5;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});for(let i=pts.length-1;i>=0;i--){const p=pts[i];ctx.lineTo(p.x-p.nx*p.width*0.5,p.y-p.ny*p.width*0.5);}ctx.closePath();ctx.fill();ctx.strokeStyle="#d6c48c";ctx.lineWidth=0.018;ctx.stroke();ctx.strokeStyle="rgba(232,228,216,0.18)";ctx.setLineDash([0.08,0.1]);ctx.lineWidth=0.012;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.setLineDash([]);for(const skid of rt.skids){if(skid.life<=0)continue;ctx.fillStyle=`rgba(38,34,26,${0.38*skid.life})`;ctx.beginPath();ctx.arc(skid.x,skid.y,0.028,0,Math.PI*2);ctx.fill();}ctx.strokeStyle="rgba(214,196,140,0.5)";ctx.lineWidth=0.014;ctx.beginPath();rt.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();if(st.aimX!=null)drawAim(st.aimX,st.aimY,rt.decision?rt.decision.pathYaw:st.yaw);drawChassis(st.x,st.y,st.yaw,st.steer,st.slipRad);ctx.restore();}
function fmt(n,d=1){return Number.isFinite(n)?n.toFixed(d):"-";}
function renderHUD(){try{const st=rt.state;const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};set("tSpeed",fmt(st.speed,2)+" m/s");set("tSlip",fmt(st.slipRad*180/Math.PI,0)+" deg");set("tPhase",st.phase);set("tLap",st.lap+" / S"+st.sector);set("tCont",fmt(st.continuity*100,0));set("hint",st.phase==="CONTROL_LOST"?"CONTROL LOST — recovering without a teleport.":st.phase==="RECOVER"?"RECOVERING — Kairos is restabilizing on the ribbon.":`1:1 RMX 2.5 · ${fmt(rt.plant.massKg,2)} kg · 257 mm WB.`);set("note",`Stock 0.92 kg / 257 mm WB / 178/171 mm track. Target ${fmt(rt.env.targetSpeedMps,2)} m/s, slip ${fmt(rt.env.targetSlipRad*180/Math.PI,0)} deg, look ${fmt(rt.env.lookAheadM,2)} m.`);set("paceEm",rt.controls.pace+" / "+fmt(rt.env.targetSpeedMps,2)+" m/s");set("attackEm",rt.controls.attack+" / "+fmt(rt.env.targetSlipRad*180/Math.PI,0)+" deg");set("lPower","POWER "+rt.controls.power);set("lMass","MASS "+rt.controls.mass+" → "+fmt(rt.plant.massKg,2)+" kg");set("lGrip","GRIP "+rt.controls.grip);set("lBias","REAR BIAS "+rt.controls.rearBias);const pause=document.getElementById("pause");if(pause){pause.className=rt.paused?"is-on":"";pause.innerHTML=rt.paused?"RESUME<em>held</em>":"PAUSE<em>live</em>";}}catch(e){}}
function chip(label,on,fn){const b=document.createElement("button");b.className="kl-chip"+(on?" is-on":"");b.textContent=label;b.onclick=fn;return b;}
function refreshChips(){const presets=document.getElementById("presets");presets.innerHTML="";Object.keys(STYLE_PRESETS).forEach(id=>presets.appendChild(chip(id.replace("_"," "),rt.controls.style===id,()=>{Object.assign(rt.controls,STYLE_PRESETS[id],{style:id});syncSliders();rt.setLiveControls(rt.controls);refreshChips();})));Object.keys(VEHICLE_PRESETS).forEach(id=>presets.appendChild(chip(id.replace("_"," "),rt.controls.vehicle===id,()=>{Object.assign(rt.controls,VEHICLE_PRESETS[id],{vehicle:id});syncSliders();rt.setLiveControls(rt.controls);refreshChips();})));presets.appendChild(chip(advanced?"HIDE ADVANCED":"CAR / TRACK",advanced,()=>{advanced=!advanced;document.getElementById("side").classList.toggle("is-open",advanced);refreshChips();}));const cams=document.getElementById("cams");cams.innerHTML="";["CHASE","CINEMATIC","TOP"].forEach(m=>{const b=document.createElement("button");b.className=camera===m?"is-on":"";b.textContent=m;b.onclick=()=>{camera=m;refreshChips();};cams.appendChild(b);});const surfaces=document.getElementById("surfaces");surfaces.innerHTML="";["dry","low","wet"].forEach(s=>{const b=document.createElement("button");b.className=rt.controls.surface===s?"is-on":"";b.textContent=s.toUpperCase();b.onclick=()=>{rt.controls.surface=s;rt.setLiveControls(rt.controls);refreshChips();};surfaces.appendChild(b);});const tracks=document.getElementById("tracks");tracks.innerHTML="";[["foundation_loop","LOOP Ø6 m"],["circuit_one","CIRCUIT"]].forEach(([id,label])=>{const b=document.createElement("button");b.className=rt.controls.trackId===id?"is-on":"";b.textContent=label;b.onclick=()=>{rt.controls.trackId=id;rt.setLiveControls(rt.controls);refreshChips();};tracks.appendChild(b);});}
function syncSliders(){["pace","attack","power","mass","grip","rearBias"].forEach(k=>{document.getElementById(k).value=rt.controls[k];});}
["pace","attack","power","mass","grip","rearBias"].forEach(k=>{document.getElementById(k).addEventListener("input",e=>{rt.controls[k]=Number(e.target.value);if(k==="pace"||k==="attack")rt.controls.style="CUSTOM";else rt.controls.vehicle="CUSTOM";rt.setLiveControls(rt.controls);refreshChips();});});
function paintRuns(){document.getElementById("runs").innerHTML=runs.map(r=>`<div><strong>${r.label}</strong><div>P${r.pace} A${r.attack}</div><div>avg ${fmt(r.avgSpeed,2)} m/s</div><div>slip ${fmt(r.avgSlipDeg,0)}</div><div>cont ${fmt(r.continuity*100,0)}</div></div>`).join("");}
document.getElementById("resetCar").onclick=()=>{rt.resetCar();renderHUD();};
document.getElementById("resetRun").onclick=()=>{rt.resetCar();runs=[];paintRuns();renderHUD();};
document.getElementById("resetSetup").onclick=()=>{rt.resetSetup();syncSliders();runs=[];paintRuns();refreshChips();renderHUD();};
document.getElementById("pause").onclick=()=>{rt.paused=!rt.paused;renderHUD();};
document.getElementById("store").onclick=()=>{runs=[rt.summarize("R"+(runs.length+1)),...runs].slice(0,4);paintRuns();};
fit();refreshChips();renderHUD();window.addEventListener("resize",fit);
let last=performance.now(),acc=0;
function loop(now){requestAnimationFrame(loop);const raw=Math.min(0.05,(now-last)/1000);last=now;acc+=raw;while(acc>=DT){rt.step(DT);acc-=DT;}draw();renderHUD();}
requestAnimationFrame(loop);
